// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

package sqlc

import (
	"context"
)

const listActiveCompanies = `-- name: ListActiveCompanies :many
SELECT company_id, name, ats, slug, active, created_at
FROM companies
WHERE active = TRUE
ORDER BY name
`

func (q *Queries) ListActiveCompanies(ctx context.Context) ([]Company, error) {
	rows, err := q.db.QueryContext(ctx, listActiveCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.CompanyID,
			&i.Name,
			&i.Ats,
			&i.Slug,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCompanyKeys = `-- name: ListAllCompanyKeys :many
SELECT ats, slug FROM companies
`

type ListAllCompanyKeysRow struct {
	Ats  string `json:"ats"`
	Slug string `json:"slug"`
}

// All (ats, slug) pairs regardless of status, for discovery dedup.
func (q *Queries) ListAllCompanyKeys(ctx context.Context) ([]ListAllCompanyKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllCompanyKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllCompanyKeysRow
	for rows.Next() {
		var i ListAllCompanyKeysRow
		if err := rows.Scan(&i.Ats, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCompany = `-- name: UpsertCompany :exec
INSERT INTO companies (company_id, name, ats, slug)
VALUES ($1, $2, $3, $4)
ON CONFLICT (ats, slug) DO UPDATE SET name = EXCLUDED.name
`

type UpsertCompanyParams struct {
	CompanyID string `json:"company_id"`
	Name      string `json:"name"`
	Ats       string `json:"ats"`
	Slug      string `json:"slug"`
}

// Used to seed the catalog. On conflict we refresh the display name but leave
// `active` untouched, so a company an admin disabled stays disabled across restarts.
func (q *Queries) UpsertCompany(ctx context.Context, arg UpsertCompanyParams) error {
	_, err := q.db.ExecContext(ctx, upsertCompany,
		arg.CompanyID,
		arg.Name,
		arg.Ats,
		arg.Slug,
	)
	return err
}
