// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	models "github.com/gautamsardana/relay/internal/models"
)

type RunStatus string

const (
	RunStatusInit       RunStatus = "init"
	RunStatusProcessing RunStatus = "processing"
	RunStatusSuccess    RunStatus = "success"
	RunStatusFailed     RunStatus = "failed"
)

func (e *RunStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RunStatus(s)
	case string:
		*e = RunStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RunStatus: %T", src)
	}
	return nil
}

type NullRunStatus struct {
	RunStatus RunStatus `json:"run_status"`
	Valid     bool      `json:"valid"` // Valid is true if RunStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRunStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RunStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RunStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRunStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RunStatus), nil
}

type StepStatus string

const (
	StepStatusInit       StepStatus = "init"
	StepStatusPending    StepStatus = "pending"
	StepStatusProcessing StepStatus = "processing"
	StepStatusSuccess    StepStatus = "success"
	StepStatusFailed     StepStatus = "failed"
	StepStatusCancelled  StepStatus = "cancelled"
)

func (e *StepStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StepStatus(s)
	case string:
		*e = StepStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for StepStatus: %T", src)
	}
	return nil
}

type NullStepStatus struct {
	StepStatus StepStatus `json:"step_status"`
	Valid      bool       `json:"valid"` // Valid is true if StepStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStepStatus) Scan(value interface{}) error {
	if value == nil {
		ns.StepStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StepStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStepStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StepStatus), nil
}

type WorkerStatus string

const (
	WorkerStatusActive   WorkerStatus = "active"
	WorkerStatusPaused   WorkerStatus = "paused"
	WorkerStatusArchived WorkerStatus = "archived"
)

func (e *WorkerStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkerStatus(s)
	case string:
		*e = WorkerStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkerStatus: %T", src)
	}
	return nil
}

type NullWorkerStatus struct {
	WorkerStatus WorkerStatus `json:"worker_status"`
	Valid        bool         `json:"valid"` // Valid is true if WorkerStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkerStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WorkerStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkerStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkerStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkerStatus), nil
}

type Company struct {
	CompanyID string    `json:"company_id"`
	Name      string    `json:"name"`
	Ats       string    `json:"ats"`
	Slug      string    `json:"slug"`
	Active    bool      `json:"active"`
	CreatedAt time.Time `json:"created_at"`
}

type Run struct {
	RunID      string           `json:"run_id"`
	WorkerID   string           `json:"worker_id"`
	Status     models.RunStatus `json:"status"`
	Error      sql.NullString   `json:"error"`
	StartedAt  time.Time        `json:"started_at"`
	FinishedAt sql.NullTime     `json:"finished_at"`
}

type SeenJob struct {
	ID        string    `json:"id"`
	WorkerID  string    `json:"worker_id"`
	CompanyID string    `json:"company_id"`
	JobID     string    `json:"job_id"`
	SeenAt    time.Time `json:"seen_at"`
}

type Step struct {
	StepID      string            `json:"step_id"`
	RunID       string            `json:"run_id"`
	StepNumber  int32             `json:"step_number"`
	Tool        string            `json:"tool"`
	Description string            `json:"description"`
	Input       json.RawMessage   `json:"input"`
	Output      json.RawMessage   `json:"output"`
	Status      models.StepStatus `json:"status"`
	RetryCount  int32             `json:"retry_count"`
	Error       sql.NullString    `json:"error"`
	CreatedAt   time.Time         `json:"created_at"`
	UpdatedAt   time.Time         `json:"updated_at"`
}

type User struct {
	UserID    string    `json:"user_id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

type Worker struct {
	WorkerID        string         `json:"worker_id"`
	UserID          string         `json:"user_id"`
	Name            string         `json:"name"`
	Instructions    string         `json:"instructions"`
	IntervalSeconds int32          `json:"interval_seconds"`
	Status          WorkerStatus   `json:"status"`
	ResumeText      sql.NullString `json:"resume_text"`
	RecencyWeight   int32          `json:"recency_weight"`
	Category        string         `json:"category"`
	Keywords        string         `json:"keywords"`
	LocationPref    string         `json:"location_pref"`
	Level           string         `json:"level"`
	YearsExperience int32          `json:"years_experience"`
	NextRunAt       sql.NullTime   `json:"next_run_at"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}
