// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package sqlc

import (
	"context"
	"database/sql"

	models "github.com/gautamsardana/relay/internal/models"
)

const createRun = `-- name: CreateRun :one
INSERT INTO workflow_runs (run_id, worker_id, status)
VALUES ($1, $2, $3)
RETURNING run_id, worker_id, status, error, started_at, finished_at
`

type CreateRunParams struct {
	RunID    string           `json:"run_id"`
	WorkerID string           `json:"worker_id"`
	Status   models.RunStatus `json:"status"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (WorkflowRun, error) {
	row := q.db.QueryRowContext(ctx, createRun, arg.RunID, arg.WorkerID, arg.Status)
	var i WorkflowRun
	err := row.Scan(
		&i.RunID,
		&i.WorkerID,
		&i.Status,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getRunByID = `-- name: GetRunByID :one
SELECT run_id, worker_id, status, error, started_at, finished_at
FROM workflow_runs
WHERE run_id = $1
`

func (q *Queries) GetRunByID(ctx context.Context, runID string) (WorkflowRun, error) {
	row := q.db.QueryRowContext(ctx, getRunByID, runID)
	var i WorkflowRun
	err := row.Scan(
		&i.RunID,
		&i.WorkerID,
		&i.Status,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listRunsByWorker = `-- name: ListRunsByWorker :many
SELECT run_id, worker_id, status, error, started_at, finished_at
FROM workflow_runs
WHERE worker_id = $1
ORDER BY started_at DESC
`

func (q *Queries) ListRunsByWorker(ctx context.Context, workerID string) ([]WorkflowRun, error) {
	rows, err := q.db.QueryContext(ctx, listRunsByWorker, workerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRun
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(
			&i.RunID,
			&i.WorkerID,
			&i.Status,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunStatus = `-- name: UpdateRunStatus :exec
UPDATE workflow_runs
SET status = $2, error = $3, finished_at = CASE WHEN $2 IN ('success', 'failed') THEN NOW() ELSE NULL END
WHERE run_id = $1
`

type UpdateRunStatusParams struct {
	RunID  string           `json:"run_id"`
	Status models.RunStatus `json:"status"`
	Error  sql.NullString   `json:"error"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateRunStatus, arg.RunID, arg.Status, arg.Error)
	return err
}
