// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seen_jobs.sql

package sqlc

import (
	"context"
)

const listSeenJobKeys = `-- name: ListSeenJobKeys :many
SELECT company_id, job_id
FROM seen_jobs
WHERE worker_id = $1
`

type ListSeenJobKeysRow struct {
	CompanyID string `json:"company_id"`
	JobID     string `json:"job_id"`
}

// Returns the (company_id, job_id) pairs this worker has already been shown,
// so job_search can filter them out of a new run.
func (q *Queries) ListSeenJobKeys(ctx context.Context, workerID string) ([]ListSeenJobKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listSeenJobKeys, workerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeenJobKeysRow
	for rows.Next() {
		var i ListSeenJobKeysRow
		if err := rows.Scan(&i.CompanyID, &i.JobID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSeenJob = `-- name: RecordSeenJob :exec
INSERT INTO seen_jobs (id, worker_id, company_id, job_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (worker_id, company_id, job_id) DO NOTHING
`

type RecordSeenJobParams struct {
	ID        string `json:"id"`
	WorkerID  string `json:"worker_id"`
	CompanyID string `json:"company_id"`
	JobID     string `json:"job_id"`
}

// Marks a job as shown to this worker. Idempotent via the unique constraint,
// so a retried score_jobs step can re-record without error.
func (q *Queries) RecordSeenJob(ctx context.Context, arg RecordSeenJobParams) error {
	_, err := q.db.ExecContext(ctx, recordSeenJob,
		arg.ID,
		arg.WorkerID,
		arg.CompanyID,
		arg.JobID,
	)
	return err
}
