// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: steps.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"

	json "encoding/json"
	models "github.com/gautamsardana/relay/internal/models"
)

const createStep = `-- name: CreateStep :one
INSERT INTO steps (step_id, workflow_id, step_number, tool, description, input, output, status, retry_count, error)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING step_id, workflow_id, step_number, tool, description, input, output, status, retry_count, error, created_at, updated_at
`

type CreateStepParams struct {
	StepID      string            `json:"step_id"`
	WorkflowID  string            `json:"workflow_id"`
	StepNumber  int32             `json:"step_number"`
	Tool        string            `json:"tool"`
	Description string            `json:"description"`
	Input       json.RawMessage   `json:"input"`
	Output      json.RawMessage   `json:"output"`
	Status      models.StepStatus `json:"status"`
	RetryCount  int32             `json:"retry_count"`
	Error       sql.NullString    `json:"error"`
}

func (q *Queries) CreateStep(ctx context.Context, arg CreateStepParams) (Step, error) {
	row := q.db.QueryRowContext(ctx, createStep,
		arg.StepID,
		arg.WorkflowID,
		arg.StepNumber,
		arg.Tool,
		arg.Description,
		arg.Input,
		arg.Output,
		arg.Status,
		arg.RetryCount,
		arg.Error,
	)
	var i Step
	err := row.Scan(
		&i.StepID,
		&i.WorkflowID,
		&i.StepNumber,
		&i.Tool,
		&i.Description,
		&i.Input,
		&i.Output,
		&i.Status,
		&i.RetryCount,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStepById = `-- name: GetStepById :one
SELECT step_id, workflow_id, step_number, tool, description, input, output, status, retry_count, error, created_at, updated_at
FROM steps
WHERE step_id = $1
`

func (q *Queries) GetStepById(ctx context.Context, stepID string) (Step, error) {
	row := q.db.QueryRowContext(ctx, getStepById, stepID)
	var i Step
	err := row.Scan(
		&i.StepID,
		&i.WorkflowID,
		&i.StepNumber,
		&i.Tool,
		&i.Description,
		&i.Input,
		&i.Output,
		&i.Status,
		&i.RetryCount,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStepsByWorkflow = `-- name: ListStepsByWorkflow :many
SELECT step_id, workflow_id, step_number, tool, description, input, output, status, retry_count, error, created_at, updated_at
FROM steps
WHERE workflow_id = $1
ORDER BY step_number ASC
`

func (q *Queries) ListStepsByWorkflow(ctx context.Context, workflowID string) ([]Step, error) {
	rows, err := q.db.QueryContext(ctx, listStepsByWorkflow, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Step
	for rows.Next() {
		var i Step
		if err := rows.Scan(
			&i.StepID,
			&i.WorkflowID,
			&i.StepNumber,
			&i.Tool,
			&i.Description,
			&i.Input,
			&i.Output,
			&i.Status,
			&i.RetryCount,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStepStatus = `-- name: UpdateStepStatus :exec
UPDATE steps
SET status = $2, updated_at = now()
WHERE step_id = $1
`

type UpdateStepStatusParams struct {
	StepID string            `json:"step_id"`
	Status models.StepStatus `json:"status"`
}

func (q *Queries) UpdateStepStatus(ctx context.Context, arg UpdateStepStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateStepStatus, arg.StepID, arg.Status)
	return err
}
