// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflows.sql

package sqlc

import (
	"context"

	models "github.com/gautamsardana/relay/internal/models"
)

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflows (workflow_id, request, status)
VALUES ($1, $2, $3)
RETURNING workflow_id, request, status, created_at, updated_at
`

type CreateWorkflowParams struct {
	WorkflowID string                `json:"workflow_id"`
	Request    string                `json:"request"`
	Status     models.WorkflowStatus `json:"status"`
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, createWorkflow, arg.WorkflowID, arg.Request, arg.Status)
	var i Workflow
	err := row.Scan(
		&i.WorkflowID,
		&i.Request,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowById = `-- name: GetWorkflowById :one
SELECT workflow_id, request, status, created_at, updated_at
FROM workflows
WHERE workflow_id = $1
`

func (q *Queries) GetWorkflowById(ctx context.Context, workflowID string) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowById, workflowID)
	var i Workflow
	err := row.Scan(
		&i.WorkflowID,
		&i.Request,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkflows = `-- name: ListWorkflows :many
SELECT workflow_id, request, status, created_at, updated_at
FROM workflows
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListWorkflowsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListWorkflows(ctx context.Context, arg ListWorkflowsParams) ([]Workflow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflows, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workflow
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.WorkflowID,
			&i.Request,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkflowStatus = `-- name: UpdateWorkflowStatus :exec
UPDATE workflows
SET status = $2, updated_at = now()
WHERE workflow_id = $1
`

type UpdateWorkflowStatusParams struct {
	WorkflowID string                `json:"workflow_id"`
	Status     models.WorkflowStatus `json:"status"`
}

func (q *Queries) UpdateWorkflowStatus(ctx context.Context, arg UpdateWorkflowStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkflowStatus, arg.WorkflowID, arg.Status)
	return err
}
