// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workers.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createWorker = `-- name: CreateWorker :one
INSERT INTO workers (worker_id, user_id, name, instructions, interval_seconds, status, resume_text, recency_weight, next_run_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING worker_id, user_id, name, instructions, interval_seconds, status, resume_text, recency_weight, next_run_at, created_at, updated_at
`

type CreateWorkerParams struct {
	WorkerID        string         `json:"worker_id"`
	UserID          string         `json:"user_id"`
	Name            string         `json:"name"`
	Instructions    string         `json:"instructions"`
	IntervalSeconds int32          `json:"interval_seconds"`
	Status          WorkerStatus   `json:"status"`
	ResumeText      sql.NullString `json:"resume_text"`
	RecencyWeight   int32          `json:"recency_weight"`
	NextRunAt       sql.NullTime   `json:"next_run_at"`
}

func (q *Queries) CreateWorker(ctx context.Context, arg CreateWorkerParams) (Worker, error) {
	row := q.db.QueryRowContext(ctx, createWorker,
		arg.WorkerID,
		arg.UserID,
		arg.Name,
		arg.Instructions,
		arg.IntervalSeconds,
		arg.Status,
		arg.ResumeText,
		arg.RecencyWeight,
		arg.NextRunAt,
	)
	var i Worker
	err := row.Scan(
		&i.WorkerID,
		&i.UserID,
		&i.Name,
		&i.Instructions,
		&i.IntervalSeconds,
		&i.Status,
		&i.ResumeText,
		&i.RecencyWeight,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkerByID = `-- name: GetWorkerByID :one
SELECT worker_id, user_id, name, instructions, interval_seconds, status, resume_text, recency_weight, next_run_at, created_at, updated_at
FROM workers
WHERE worker_id = $1
`

func (q *Queries) GetWorkerByID(ctx context.Context, workerID string) (Worker, error) {
	row := q.db.QueryRowContext(ctx, getWorkerByID, workerID)
	var i Worker
	err := row.Scan(
		&i.WorkerID,
		&i.UserID,
		&i.Name,
		&i.Instructions,
		&i.IntervalSeconds,
		&i.Status,
		&i.ResumeText,
		&i.RecencyWeight,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueWorkers = `-- name: ListDueWorkers :many
SELECT worker_id, user_id, name, instructions, interval_seconds, status, resume_text, recency_weight, next_run_at, created_at, updated_at
FROM workers
WHERE status = 'active' AND next_run_at <= NOW()
`

func (q *Queries) ListDueWorkers(ctx context.Context) ([]Worker, error) {
	rows, err := q.db.QueryContext(ctx, listDueWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worker
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.WorkerID,
			&i.UserID,
			&i.Name,
			&i.Instructions,
			&i.IntervalSeconds,
			&i.Status,
			&i.ResumeText,
			&i.RecencyWeight,
			&i.NextRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkersByUser = `-- name: ListWorkersByUser :many
SELECT worker_id, user_id, name, instructions, interval_seconds, status, resume_text, recency_weight, next_run_at, created_at, updated_at
FROM workers
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWorkersByUser(ctx context.Context, userID string) ([]Worker, error) {
	rows, err := q.db.QueryContext(ctx, listWorkersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worker
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.WorkerID,
			&i.UserID,
			&i.Name,
			&i.Instructions,
			&i.IntervalSeconds,
			&i.Status,
			&i.ResumeText,
			&i.RecencyWeight,
			&i.NextRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkerNextRunAt = `-- name: UpdateWorkerNextRunAt :exec
UPDATE workers
SET next_run_at = $2, updated_at = NOW()
WHERE worker_id = $1
`

type UpdateWorkerNextRunAtParams struct {
	WorkerID  string       `json:"worker_id"`
	NextRunAt sql.NullTime `json:"next_run_at"`
}

func (q *Queries) UpdateWorkerNextRunAt(ctx context.Context, arg UpdateWorkerNextRunAtParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkerNextRunAt, arg.WorkerID, arg.NextRunAt)
	return err
}

const updateWorkerStatus = `-- name: UpdateWorkerStatus :exec
UPDATE workers
SET status = $2, updated_at = NOW()
WHERE worker_id = $1
`

type UpdateWorkerStatusParams struct {
	WorkerID string       `json:"worker_id"`
	Status   WorkerStatus `json:"status"`
}

func (q *Queries) UpdateWorkerStatus(ctx context.Context, arg UpdateWorkerStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkerStatus, arg.WorkerID, arg.Status)
	return err
}
